export const PROGRAMMING_LANGUAGES = [
  { label: "JavaScript", value: "javascript" },
  { label: "Python", value: "python" },
  { label: "Java", value: "java" },
  { label: "C#", value: "csharp" },
  { label: "C++", value: "cpp" },
  { label: "PHP", value: "php" },
  { label: "Ruby", value: "ruby" },
  { label: "CSS", value: "css" },
  { label: "HTML", value: "markup" },
  { label: "Swift", value: "swift" },
  { label: "Kotlin", value: "kotlin" },
  { label: "TypeScript", value: "typescript" },
  { label: "SQL", value: "sql" },
  { label: "Go", value: "go" },
  { label: "R", value: "r" },
  { label: "Perl", value: "perl" },
  { label: "Scala", value: "scala" },
  { label: "Bash", value: "bash" },
  { label: "Lua", value: "lua" },
  { label: "Rust", value: "rust" },
];
